### PR TITLE
Better handle unusual extensions

### PR DESCRIPTION
**Pull request by ngfreiter**
## Description

Fixes https://github.com/FHIR/GoFSH/issues/157.

This PR adds two special cases to the `RemoveExtensionURLAssignmentRulesOptimizer`.

The first case occurs when the JSON processed by GoFSH has the pattern:
```json
{
  "id": "Extension.extension:date-month-absent-reason.url",
  "path": "Extension.extension.url",
  "type": [{ "code": "uri" }],
  "fixedUri": "month-absent-reason"
}
```
where the `url` of an inline extension is fixed to a value different that the `sliceName` of the element. This will result in a line of FSH like:
```
* extension[date-year-absent-reason].url = "year-absent-reason" (exactly)
```
which causes an error in SUSHI, since `url` has already been automatically fixed by SUSHI to be `data-year-absent-reason`. This PR updates the optimizer to log an error, and prefer the `sliceName` by removing the rule which fixes `url`. So no rule like the line of FSH above will be generated. Note that this doesn't change the JSON generated by SUSHI, since this rule was ignored by SUSHI as an error anyway. But this change places the error in GoFSH instead of SUSHI, and makes it more clear.

The second case occurs when the JSON processed by GoFSH has the pattern:
```json
{
  "id": "Observation.extension:injuryLocation",
  "path": "Observation.extension",
  "sliceName": "injuryLocation",
  "min": 0,
  "max": "1"
},
{
  "id": "Observation.extension:injuryLocation.url",
  "path": "Observation.extension.url",
  "min": 1,
  "max": "1",
  "fixedUri": "http://hl7.org/fhir/us/vrdr/StructureDefinition/Observation-Location"
},
```
In this case, the URL of the extension is being indicated by the `fixedUri`. This will result in FSH like:
```
* extension contains injuryLocation 0..1
* extension[injuryLocation].url = "http://hl7.org/fhir/us/vrdr/StructureDefinition/Observation-Location" (exactly)
```
But SUSHI processes this as if you are trying to set an inline extension, which is not allowed on profiles, and results in errors. Instead the FSH should look like:
```
extension contains ObservationLocation named injuryLocation 0..1
```
where `ObservationLocation` is the name of the extension with url `http://hl7.org/fhir/us/vrdr/StructureDefinition/Observation-Location`. This PR updates GoFSH to log an error when it encounters this situation, and generate FSH using the `named` keyword, which allows SUSHI to process without error. Note that this is a little unusual, because we are purposefully creating FSH which generates JSON which will differ from the original JSON. But the JSON generated by SUSHI will have the same meaning as the original, and uses the preferred style, so I think it is justified in this case.

## Testing

To test this, I suggest downloading the [VRDR package](https://build.fhir.org/ig/HL7/vrdr/downloads.html). Then on `master`, run `gofsh -f -o build-master` on it. You should see a clean `gofsh` run, but `sushi` errors. Then on this branch, run `gofsh -f -o build-branch`. You should see the errors added in this PR logged from `gofsh`, and `sushi` should finish with only two errors (unrelated to this PR).

Then compare the generated FSH in `build-master` and `build-branch` and ensure it makes sense.

Then compare the SUSHI generated JSON in `build-master` and `build-branch` and ensure it also makes sense.

### CODE REVIEW

**Review by cmoesel — CHANGES_REQUESTED** [review]
> This PR updates the optimizer to log an error, and prefer the sliceName by removing the rule which fixes url.

I think we actually should go the other way, preferring the fixed `url` and changing the `sliceName`.  The fixed `url` is used in the actual instance of the extension, so if we change it, we invalidate all existing instances of that extension.  The `sliceName`, on the other hand, is just a detail of the metadata and does not affect the actual serialization of the extension.

Changing the slice name is probably a lot harder, but I think it's the right way to go. Although now that I think of it, it's kind of unfortunate that we rely on the slice name and fixed URL to match -- because I don't think the spec requires it.  So I'd also be open to an approach that loosens things up to allow for this use case and better preserves the round-trip (but that probably requires fixes to SUSHI).

**Comment by ngfreiter** [comment]
Ok @cmoesel, updated to prefer the `url` and not the `sliceName` in https://github.com/FHIR/GoFSH/pull/158/commits/505e9149f31c492d7411696b633964ca8e71fb5b.

**Review by cmoesel — COMMENTED** [review]
I've tried running the test using VRDR as you suggested -- but I am getting different results than you described.  While I see that your fixes have been applied, I am ending up with **7** SUSHI errors even on this PR branch (vs the **2** you said to expect).

The extra errors all stem from this root cause error:
> error Cannot create injuryLocation extension; unable to locate extension definition for: ObservationLocation.

This is based on this FSH:
```
* extension contains ObservationLocation named injuryLocation 0..1
```

Looking into it, the problem is that `Observation` is defined as a `Profile` with `Parent: Extension` rather than being defined as an `Extension`.  This seems like another issue that we should investigate and fix -- although I am confused that you didn't encounter it yourself.

The other comment I have is that when we produce a _named_ extension (i.e., adding the `type.profile`), I wonder if that should be a _warning_ rather than an error -- since it is semantically the same and actually improves best practice.  Logging it as an error makes it sound bad when, in some ways, it's good.

**Comment by ngfreiter** [comment]
> I've tried running the test using VRDR as you suggested -- but I am getting different results than you described. While I see that your fixes have been applied, I am ending up with **7** SUSHI errors even on this PR branch (vs the **2** you said to expect).
> 
> The extra errors all stem from this root cause error:
> 
> > error Cannot create injuryLocation extension; unable to locate extension definition for: ObservationLocation.
> 
> This is based on this FSH:
> 
> ```
> * extension contains ObservationLocation named injuryLocation 0..1
> ```
> 
> Looking into it, the problem is that `Observation` is defined as a `Profile` with `Parent: Extension` rather than being defined as an `Extension`. This seems like another issue that we should investigate and fix -- although I am confused that you didn't encounter it yourself.
> 
> The other comment I have is that when we produce a _named_ extension (i.e., adding the `type.profile`), I wonder if that should be a _warning_ rather than an error -- since it is semantically the same and actually improves best practice. Logging it as an error makes it sound bad when, in some ways, it's good.

Ah I actually do see those errors. I had fixed that issue in the package early on in my testing, and forgotten I did it. Those errors happen because the `ObservationLocation` SD is for an `Extension`, but has `kind` set to `resource`, which I think is pretty clearly an error. I think in this case we should ignore the `kind` and only trust the `type`. Do you think it should be an error or warning?

**Comment by cmoesel** [comment]
> I think in this case we should ignore the `kind` and only trust the `type`.
What do you mean by "in this case" and where would this change (to ignore the `kind` go)?  Are you suggesting that SUSHI should allow `extension contains` with a profile of an `Extension` that has `kind: resource`?  I think we fish for extensions here, so would that mean changing the fisher?  Might there be negative consequences if the fisher can return extensions w/ `kind: resource`?  Or am I misunderstanding what you're suggesting?

> Do you think it should be an error or warning?

If you're referring to my suggestion that adding `type.profile` could be an error or a warning, I think I'd lean toward _warning_ myself, but I'm willing to be wrong on this one if you disagree.

**Comment by cmoesel** [comment]
Oh wait.  I should have read my own previous comment before commenting again.  I was thinking that the bad extension definition (`kind: resource`) was in a dependency.  But it's in the project, so I suspect you mean to ignore kind and generate and `Extension` rather than a `Profile`.  That makes a lot more sense!

Yeah, I think we should do that. Even if you do want to create a _profile_ on an extension, this would _not_ change its kind.  So I think any definition with `type: Extension` and `kind: resource` is flat out wrong -- so I think it's OK to fix it even if it breaks the round trip...  For this one, I would log an... error?  It' s definitely wronger (?) than the previous issue.

**Comment by ngfreiter** [comment]
Ok @cmoesel, the latest two commits should address your comments.

**Review by julianxcarter — APPROVED** [review]

**Review by cmoesel — APPROVED** [review]
I've retested this and everything checks out.  Definitely an improvement!  Thanks, @ngfreiter!

**Pull request merged**
