### PR TITLE
Fix bug with choice slices

### PR DESCRIPTION
**Pull request by ngfreiter**
Fixes https://github.com/FHIR/GoFSH/issues/122.

When someone has a `sliceName` specified in the differential on the choice slice, SUSHI doesn't really know how to handle that situation, see this example (pardon my xml):
```xml
<element id="Extension.value[x]:valueReference">
      <path value="Extension.valueReference"/>
      <sliceName value="valueReference"/>
      <min value="1"/>
      <type>
        <code value="Reference"/>
        <targetProfile value="http://hl7.org/fhir/StructureDefinition/HealthcareService"/>
      </type>
    </element>
```
I wasn't sure there was a good way to make this work in SUSHI using `contains` rules, so in this case I felt like it results in more clear FSH to just not process this as a `contains` rule. But I may be missing something about how this should be written as FSH, so let me know.

### CODE REVIEW

**Review by cmoesel — CHANGES_REQUESTED** [review]
This fix is a bit too agressive now.  If you run it on the [au-base xml definitions](http://build.fhir.org/ig/hl7au/au-fhir-base/definitions.xml.zip) and compare to what is produced by gofsh master, you'll see that some `contains` statements are dropped when they shouldn't be.

For example:
image

and

image

I think this is because the new code looks for `[x]:` _anywhere_ in the path when it really should only be looking at it in the tail of the path.

**Comment by cmoesel** [comment]
I've pushed a fix for the issue I identified above.  Note that this doesn't address _all_ extension-related issues in the au-base IG.  There are some extensions where they have ids that combine the shortcut syntax _and_ the slicename (e.g., `Extension.valueIdentifier:valueIdentifier`.  This PR does not fix that case because the `id` does not have the `[x]` in it.

I'm not sure that is even a valid `id` anyway, so I do not plan to address it in this PR.

**Review by cmoesel — APPROVED** [review]
I'm approving this now that it contains my additional fix.  While there are still some issues in the au-base IG, they're related to ids that I'm not sure are valid.  We should find out if they are before spending too much time trying to fix them.  So I propose we accept this PR as it is now.

We still need another reviewer on this.

**Review by jafeltra — APPROVED** [review]
This looks good to me. I tested it out using the XML definitions and comparing the differences to what the current version of gofsh generated, and the differences all made sense to me!

**Pull request merged**
