### PR TITLE
Remove extra space

### PR DESCRIPTION
**Pull request by ngfreiter**
There was an extra space in an error message, but this PR gets rid of it.

### CODE REVIEW

**Comment by ngfreiter** [comment]
Oh my we test for the presence of that extra space. I guess it was more important than I gave it credit for.

**Review by julianxcarter — DISMISSED** [review]
Looks good to me!

**Comment by cmoesel** [comment]
Wait.  Who says that two spaces after a period constitutes an "extra space"?

**Comment by ngfreiter** [comment]
> Wait. Who says that two spaces after a period constitutes an "extra space"?

[Nearly all style guides](https://www.instructionalsolutions.com/blog/one-space-vs-two-after-period#:~:text=Nearly%20all%20style%20guides%20agree%20that%20one%20space%20is%20correct.&text=The%20Publication%20Manual%20of%20the,space%20in%20its%202019%20update) 😉

**Review by julianxcarter — APPROVED** [review]
This looks even better to me now!

**Comment by ngfreiter** [comment]
> Wait. Who says that two spaces after a period constitutes an "extra space"?

But perhaps not [science](https://www.theatlantic.com/science/archive/2018/05/two-spaces-after-a-period/559304/)???

**Comment by ngfreiter** [comment]
> Wait. Who says that two spaces after a period constitutes an "extra space"?

But truthfully, the fact that in this specific message, and in the other GoFSH messages I was seeing, we used 1 space, so I just thought we should be consistent.

**Comment by cmoesel** [comment]
I refuse to approve this PR, but neither will I reject it.  I leave it to the gods to determine its fate.

**Review by jafeltra — APPROVED** [review]
I _guess_ I'll approve this PR. But just watch out for the PR I submit that swaps all single spaces to double.

**Pull request merged**
