### PR TITLE
The big one oh oh

### PR DESCRIPTION
**Pull request by cmoesel**
The moment you've all been waiting for...

### CODE REVIEW

**Review by ngfreiter — APPROVED** [review]
Tested on several IGs and it looks good to me.

**Comment by cmoesel** [comment]
BTW -- I rebased this on master since there were two bug fixes since I issued this PR.  It's ready for re-review if anyone wants it.

**Comment by julianxcarter** [comment]
Testing this now!

**Review by julianxcarter — APPROVED** [review]
I've tested on a few IGs and it looks good to me!

**Comment by cmoesel** [comment]
I found one more issue that I think requires a fix, but it's an easy fix.  So knocking this back into draft.

**Comment by cmoesel** [comment]
Alright.  This is a go!

**Pull request merged**
